import Vue from 'vue'

import { Button, NavBar, Tabbar, TabbarItem, Col, Row, Image as VanImage, Cell, CellGroup, Icon, Search, Tag, Toast, Tab, Tabs, Divider, List, PullRefresh, Swipe, SwipeItem, Lazyload, Grid, GridItem, DropdownMenu, DropdownItem, Empty, Popup, Loading, Circle, Dialog, Form, Field } from 'vant'

Vue.use(Form)
Vue.use(Field)
Vue.use(Dialog)
Vue.use(Circle)
Vue.use(Loading)
Vue.use(Popup)
Vue.use(Empty)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(Divider)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Toast)
Vue.use(Tag)
Vue.use(Search)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(VanImage)
Vue.use(NavBar)
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Col)
Vue.use(Row)
Vue.use(Icon)
Vue.use(Lazyload)
